--- #YAML:1.0
name:                vshnu
version:             1.0300
abstract:            a visual shell supplement
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Term::ANSIColor:               0
    Term::Screen:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Steve Kinzler <kinzler@cs.indiana.edu>
