#!/usr/bin/perl
BEGIN { unshift @INC, "$ENV{'HOME'}/perl",
		      "$ENV{'HOME'}/libp/perl", "$ENV{'HOME'}/lib/perl",
		      "$ENV{'HOME'}/libp",	"$ENV{'HOME'}/lib" }

$default_vshnucfg = '';

$debug	  = 0;
$debug_ch = 0;

# vshnu - an enhanced vsh-like visual shell supplement in Perl
# Steve Kinzler, kinzler@cs.indiana.edu, Aug 99/Mar 00/Sep 00
# see website http://www.cs.indiana.edu/~kinzler/vshnu/
# http://www.cs.indiana.edu/~kinzler/home.html#unix

###############################################################################
## Change log #################################################################

($vname, $version) = qw(vshnu 1.0128);

# 1.0000   7 Nov 2000	Initial public release
# 1.0003  13 Dec 2000	Version format x.y.z -> x.0y0z
# 1.0005  26 Jan 2001	Use most specific LS_COLORS match
# 1.0010   2 Jul 2001	Improve function key support
# 1.0013  27 Mar 2002	Use VSHNUTMP to enable tmp files and specify location
# 1.0100  29 Mar 2002	Recognize VSHNUCWD and VSHNUENV for tmp file basenames
# 1.0101   1 Apr 2002	Add ifopt and unlessopt utility subs
# 1.0102   3 Apr 2002	Fix bug in ifopt and unlessopt for older perls
# 1.0103  16 Apr 2002	Add "use Data::Dumper" and &vardump
# 1.0104  23 Apr 2002	Report $! errors from &sh and &shell
# 1.0105  14 Jun 2002	Add $stty_cooked and $stty_raw
# 1.0106  25 Nov 2002	Support non-ANSI non-color terminals
# 1.0107  23 Jan 2003	Fix readline for prompts w/ non-visible characters
# 1.0108   4 Jun 2003	Include ~/perl in @INC; Use HOSTNAME if no HOST
# 1.0109  11 Jun 2003	Fixes for non-Gnu ReadLines; Versions support
# 1.0110  13 Jun 2003	Use only one ReadLine instance, fix history doubling
# 1.0111  18 Jun 2003	Fixes for perl 5.8 safe signals and Gnu ReadLine resize
# 1.0112  19 Jun 2003	Suppress consecutive duplicates in readline histories
# 1.0113   1 Jul 2003	Suppress any program name label from long listings
# 1.0114   2 Jul 2003	Add insert-vshnu-chosen Gnu ReadLine function
# 1.0115   3 Jul 2003	Use Sys::Hostname if no HOST or HOSTNAME
# 1.0116   8 Jul 2003	Propogate @choose to shell; -V command line flag
# 1.0117  10 Jul 2003	Fix &long bug for @_ longls's on empty file sets
# 1.0118  11 Jul 2003	Use optional Filesys::DiskFree and add &disks
# 1.0119  11 Jul 2003	Separate ReadLine histories for shells, files, etc
# 1.0120   4 Dec 2003	Use LS_COLORS2 (appended to LS_COLORS) if available
# 1.0121   3 Jun 2004	View trailing spaces in filenames; Add &diskdevs
# 1.0122   4 Jun 2004	Add &longtrunc for truncation function spec/toggle
# 1.0123   7 Jun 2004	Add &pwd and &diskspace; Enhanced &getmark
# 1.0124  29 Jun 2004	Generalize insert-vshnu-chosen to insert-vshnu
# 1.0125   2 Nov 2004	Add $_f and $_fq dotype variables for full pathnames
# 1.0126  27 Nov 2004	Add &filecounts and &filecount
# 1.0127  28 Nov 2004	Color file paths as directories; Add sort bydepth
# 1.0128  31 Jan 2005	Add &expand, &collapse and &expandtoggle aliases

###############################################################################
## Modules setup ##############################################################

$tmpcwd = (! defined $ENV{'VSHNUTMP'}) ? '' :
	  (($ENV{'VSHNUTMP'} ne '') ? $ENV{'VSHNUTMP'}    : '/tmp') .
	  (($ENV{'VSHNUCWD'} ne '') ? "/$ENV{'VSHNUCWD'}" : "/vsh$$");
$tmpenv = (! defined $ENV{'VSHNUTMP'}) ? '' :
	  (($ENV{'VSHNUTMP'} ne '') ? $ENV{'VSHNUTMP'}    : '/tmp') .
	  (($ENV{'VSHNUENV'} ne '') ? "/$ENV{'VSHNUENV'}" : "/env$$");
$tmpcwd =~ s:/+:/:g; $tmpenv =~ s:/+:/:g;

require 5.002;

use	Config;
use	Sys::Hostname;
eval	'use Data::Dumper';
eval	'use Filesys::DiskFree';

require Term::Screen;
use	Term::ANSIColor;

use	Term::ReadLine;	# setenv PERL_RL {Gnu,Perl,false}, dflt best available

print("$version\n"), exit    if $ARGV[0] eq '-v';
$ARGV_V = 1, @ARGV = ()	     if $ARGV[0] eq '-V';
die "usage: $0 [ -v | -V | [ -- ] dir ... ]\nVersion $version\n"
			     if $ARGV[0] =~ /^-/ && $ARGV[0] ne '--';
die "$0: stdin not a tty\n"  unless -t;
shift @ARGV if $ARGV[0] eq '--';

&winch_off();
$rl = new Term::ReadLine 'vshnu' or die "$0: can't create readline ($!)";
&winch_on();
($rlmodule = $rl->ReadLine) =~ s/.*Term::ReadLine:://;
$rl->ornaments(0)				  if $rlmodule =~ /^Stub/i;
$rl->add_defun('insert-vshnu', \&rl_insert_vshnu) if $rlmodule eq 'Gnu';
@rlhist_ = @rlhist_shell = @rlhist_junk = @rlhist_file = ();

sub rl_insert_vshnu {
	&home(), $scr->clreos()	      if ref $$insertcmd[0];
	my $text = join(' ', &quote(eval { &cmdeval($insertcmd) }));
	$rl->insert_text($text . ' ') if $text ne '';
	$rl->forced_update_display    if ref $$insertcmd[0];
}

sub rl_bind_insert_vshnu {
	return unless $rlmodule eq 'Gnu';
	$rl->parse_and_bind("$_[0]: insert-vshnu");
}

###############################################################################
## Versions setup and subroutines #############################################

@versions = (
	'perl'			=> "$Config{'version'} $Config{'archname'}",
	'Sys::Hostname'		=> $Sys::Hostname::VERSION,
	'Data::Dumper'		=> $Data::Dumper::VERSION
				|| 'NOT INSTALLED',
	'Filesys::DiskFree'	=> $Filesys::DiskFree::VERSION
				|| 'NOT INSTALLED',
	'Term::Screen'		=> $Term::Screen::VERSION,
	'Term::ANSIColor'	=> $Term::ANSIColor::VERSION,
	'Term::ReadLine'	=> $rlmodule,
	$rl->ReadLine		=> $rl->ReadLine->VERSION,
($rlmodule ne 'Gnu') ? () :
       ('GNU Readline Library'	=> $rl->Attribs->{'library_version'}),
	'ReadLine Features'	=> join(' ', sort keys %{$rl->Features}),
	$vname			=> $version);
%versions = @versions;
do { my $n = 1; @versions = grep { $n++ % 2 } @versions };

sub addversions {
	while (@_) {
		push(@versions, $_[0]), $versions{$_[0]} = $_[1]
			unless exists $versions{$_[0]};
		shift; shift;
	}
}

sub versions {
	my @v = (@_) ? @_ : @versions;
	my $fmt = '%' . &max(map { length($_) } @v) . 's %s';
	join("\n", map { sprintf($fmt, $_, $versions{$_}) } @v) . "\n";
}

print(&versions()), exit if $ARGV_V;

###############################################################################
## Initial setup ##############################################################

$ch   = $ch_list = $err = $stty_cooked = $stty_raw = ''; $cooked = 0;
$path = $ENV{'PATH'}; $ENV{'PATH'} = "/usr/ucb:$ENV{'PATH'}";
$scr  = new Term::Screen or die "$0: cannot create screen ($!)";
$ENV{'PATH'} = $path; undef $path;	# to get /usr/ucb/stty on Solaris
$scr->noecho();
&sigs_on();

$ncolors = $scr->{TERM}->{_Co};
$color   = $ncolors > 1;
$bold    = $scr->{TERM}->Tputs('md', 1);
$reverse = $scr->{TERM}->Tputs('mr', 1) ||
	   $scr->{TERM}->Tputs('so', 1);
$normal  = $scr->{TERM}->Tputs('me', 1) ||
	   $scr->{TERM}->Tputs('se', 1);
map($ansicolor{$Term::ANSIColor::attributes{$_} + 0} = $_,
    keys %Term::ANSIColor::attributes);

$user  = &uid2name($>);
($host = $ENV{'HOST'} || $ENV{'HOSTNAME'} ||
	 eval { &hostname } || 'UNKNOWN') =~ s/\..*//;
$depth = 1;

%keymap_ = ("\034" => ['last', 'quit $vname']);

&setnorun('off'); &longlen('min'); $long = 0; &longtrunc();
require($vshnucfg = $ENV{'VSHNUCFG'} || $default_vshnucfg ||
		    ((-f "$ENV{'HOME'}/.vshnucfg") ? "$ENV{'HOME'}/.vshnucfg"
						   : 'vshnucfg.pl'));
&typemap('', 1); &keymap('', 1);
&initopts();

$mail = -f $mailbox;

@cdhist = @cdhist || map({'ls' => $_}, @ARGV);
$pwd = (@cdhist) ? $cdhist[0]{'ls'} : &pwd();
$pwd ne '' && &cd($pwd) or die "$0: cannot cd $pwd\n";
undef $pwd;

if ($insertkey ne '') {
	&rl_bind_insert_vshnu($insertkey);	# Gnu ReadLine only
	$keymap_{":$insertkey"} = $insertcmd	# only for help listing
		if $insertcmd;
}

require "dumpvar.pl" if $debug;		# to enable &dumpvar(PACKAGE, VARS)
					# and &dumpValue(DATAPTR)

###############################################################################
## Main execution loop and subroutines ########################################

&win();

while (1) {
	$ch = $scr->getch();
	$scr->flush_input();	# partly broken in Term::Screen 1.00 *shrug*
	$ch_list = &scrtruncr($ch_list . ((length($ch) > 1) ? " $ch" :
			      sprintf(' 0%o', ord $ch))) if $debug_ch;

	$cmd = &keymapcmd();
	$cdhistp = 0 unless grep { /\bcdhist\b/ } &cmdstrs($cmd);
	&cmdeval($cmd);
	&win_err() if $err ne '';
}
&quit();

sub keymapcmd {
	my $map = $keymap;
	eval "\$map = \\\%keymap_$_[0]" if defined $_[0];
	my $c   = (defined $_[1]) ? $_[1] : $ch;
	(exists $$map{$c}) ? $$map{$c} : $$map{''};
}

sub cmdeval {
	my $cmd = shift;
	&echo(&helpstr($ch, '', 8, $cmd)), &ret(),
	    $norun eq 'once' && &setnorun('off'), &win(), return
		if $norun &&
		   grep { ! /\b(cmdeval|dotype|setnorun)\b/ } &cmdstrs($cmd);
	return &myeval($cmd)	 unless ref $cmd;
	return &myeval($$cmd[0]) unless ref $$cmd[0];
	&myeval(&cmdprompt($txt_cmdprompt || 'Choice:', $cmd));
}

sub keymap {
	my $_0 = $_[0]; $_0 =~ s/^\*//;		# *map => switch not push
	my $sw = $&; my $m = '';
	($_0 ne '' && $_0 eq $keymap[$#keymap] ||
	 ! defined $_[0]) ? do { pop(@keymap); $m = $keymap[$#keymap] }  :
	($_0 eq '')	  ? do { @keymap = () }				 :
	($sw)		  ? do { pop(@keymap); push(@keymap, $m = $_0) } :
			    push(@keymap, $m = $_0);
	eval "\$keymap = \\\%keymap_$m";
	&win_time(), &home() unless $_[1];
}

sub typemap {
	my $_0 = $_[0]; $_0 =~ s/^\*//;		# *map => switch not push
	my $sw = $&; my $m = '';
	($_0 ne '' && $_0 eq $typemap[$#typemap] ||
	 ! defined $_[0]) ? do { pop(@typemap); $m = $typemap[$#typemap] } :
	($_0 eq '')	  ? do { @typemap = () }			   :
	($sw)		  ? do { pop(@typemap); push(@typemap, $m = $_0) } :
			    push(@typemap, $m = $_0);
	eval "\$typemap = \\\%typemap_$m";
	&win_time(), &home() unless $_[1];
}

sub cmdstrs {
	my $c = shift;
	(! ref $c) ? ($c) : (! ref $$c[0]) ? ($$c[0]) : map { $$_[0] } @$c;
}

sub setnorun {
	$norun = ($_[0] eq 'toggle') ? ! $norun :
		 ($_[0] eq 'once')   ? 'once'	: ($_[0] eq 'on') ? 1 : 0;
}

###############################################################################
## Screen drawing subroutines #################################################

sub winat { &win(($_[0]) x 3) }

sub win {
	$time = time;
	&ls(); &lscolors();

	$filerows     = &min($#ls + 1, $scr->{ROWS} - 4);
	$pages	      = ($filerows) ? &ceil(($#ls + 1) / $filerows) : 0;
	$havefilecols = &min($pages, int($scr->{COLS} / ($minfilelen + 4)));
	&filecols(); &longlen();
	$filecols     = &min($havefilecols, ($long) ? 1 :
			     ($maxfilecols > 0) ? $maxfilecols : 1024);
	$longlen      = &min($minlonglen, $scr->{COLS} - $minfilelen - 5);
	$filelen      = int(($scr->{COLS} - (($long) ? $longlen + 1 : 0)) /
			    ($filecols || 1)) - 4;
	&page(@_);

	@lstable = ();
	foreach ($filecol .. $filecol + $filecols - 1) {
		my @col = @ls[$_ * $filerows .. ($_ + 1) * $filerows - 1];
		push(@lstable, \@col);
	}

	my $endc = &min($filecol + $filecols, $pages);
	my $ptxt = ($filecol <= 0 && $pages <= $filecols) ? ''		   :
		   ($filecol + 1 == $endc) 		  ? "$endc/$pages" :
					  ($filecol + 1) . "-$endc/$pages";
	$scr->clrscr();
	&win_decor("$user\@$host:", $cwd, $ptxt, 0);
	&win_row2();

	%drawn = (); &setcdhist('file0', '');
	$scr->at(2, 0);
	foreach $row (0 .. $filerow - 1) {
		my $col = 0; my $file; my $out = '';
		foreach (@lstable) {
			last if ($file = $_->[$row]) eq '';
			$drawn{$file} = [$row, $col];
			$col += 4 + $filelen;
			my($s, $l) = &viewfile($file, $filelen);
			my $t = ' ' x $filelen;
			substr($t, 0, $l) = $s;
			$out .= '   ' . ((! $choose{$file}) ? ' ' :
					 &color($choose{$file}, $co_decor));
			$out .= $t;
			&setcdhist('file0', $file) if $file0 eq '';
		}
		$out =~ s/^ //; $out =~ s/\s*$//;
		print $out, "\n\r";
	}
	&win_bag(1);
	&win_long() if $long;

	&win_time();
	&win_err();
}

sub win_err {
	&home();
	$scr->puts(&color($err, $co_error)), $err = '', return if $err ne '';
	return unless $mail;

	my $size = -s $mailbox;
	&msg($txt_mail	  || 'You have mail')	  if $mail ne 'old' && $size;
	&msg($txt_newmail || 'You have new mail')
		if $mail eq 'old' && $size > $mailsize;
	($mail, $mailsize) = ('old', $size);
}

sub win_row2 {
	$where =~ s/^\s+$//;
	my @bits = ();
	push(@bits, "depth=$depth")   if $depth != 1;
	push(@bits, "opts=" . join('', sort keys %opts)) if %opts;
	push(@bits, "where={$where}") if $where =~ /\S/ &&
		! grep($altls == $_, \@choose, \@cdhist, \@dohist);
	push(@bits, "long=$longlabel")	 if $longlabel;
	push(@bits, "cols=$maxfilecols") if ! $long && $maxfilecols;
	&win_decor('', $lstitle, join(', ', @bits), 1);
}

sub win_time {
	my @bits = ();
	push(@bits, 'run=OFF')			 if $norun;
	push(@bits, $#choose + 1 . ' chosen')	 if @choose;
	push(@bits, "keys=$keymap[$#keymap]")    if $keymap[$#keymap]   ne '';
	push(@bits, "types=$typemap[$#typemap]") if $typemap[$#typemap] ne '';
	&win_decor('', join(', ', @bits), &myctime($time, &opt('s')),
		   $filerow + 2, ($long && $filelen + 5 + 57 <= $scr->{COLS})
				 ? $filelen + 5 + 57 : '');
}

sub win_decor {
	my($a, $b, $c, $r, $w) = @_;
	($a, $b, $c) = (&view($a), &view($b), &view($c));
	$w = $w || $scr->{COLS};
	$scr->at($r, 0)->clreol();
	if ($a ne '' || $b ne '') {
		my @b = &truncm($b, $w - length($a) - 1 -
				    (($c ne '') ? length($c) + 1 : 0));
		$a  = &color("$a$b[0]", $co_decor);
		$a .= $b[1] . &color($b[2], $co_decor) if $#b > 0;
		$scr->at($r, 0)->puts($a);
	}
	$scr->at($r, $w - length($c) - 1)->puts(&color($c, $co_decor))
		if $c ne '';
}

sub win_bag {
	my $row = 0; my($key, $file, $qfile, $qkey);
	my @keys = @bagkeys;
	my $x = $bagrow * ($#bagkeys + 1);
	my $y = ($bagcol - $filecol) * (4 + $filelen);
	my @files = @{$lstable[$bagcol - $filecol]}[$x .. $x + $#keys];
	my @keys2 = @keys; my @files2 = @files;

	&setcdhist('file1', ''); $point = '';
	&setcdhist('fileptr', $bagkeys[0])
		unless grep($fileptr eq $_, @bagkeys);
	map(eval "\$keymap_$_\{'POINT'} = undef", keys %bagmap);

	@usedbagkeys = @bagfiles = ();
	while (@keys2 && @files2) {
		last if ($file = shift @files2) eq '';
		push(@usedbagkeys, $key = shift @keys2);
		push(@bagfiles, $file) if $_[0];
		$fileptr = $key if $file eq $pendptr;
	}
	&fileptr('+0'); undef $pendptr;

	foreach (@usedbagkeys) {
		($key, $file) = (shift @keys, shift @files);

		($_[1]) ? $key eq $fileptr &&
			  $scr->at(2 + $x + $row, $y + 1)
			      ->puts($_[0] ? '>' : ' ')
			: $scr->at(2 + $x + $row, $y)
			      ->puts(($_[0] ? &color($key, $co_decor) : ' ')
				   . ($_[0] && $key eq $fileptr ? '>' : ' '));
		$row++;

		($qfile, $qkey) = (&evalquote($file), &evalquote($key));
		$qkey =~ s/^'?/$&\\/;
		my $fill = sub { my @__ = @_;
			grep { s/<FILE>/$qfile/g; s/<KEY>/$qkey/g; 1 } @__ };
		foreach (keys %bagmap) {
			my $act = $bagmap{$_};
			$act = (! ref $act)	? [&$fill($act), ''] :
			       (! ref $$act[0]) ? [&$fill(@$act)]    :
					[map { [&$fill(@$_)] } @$act];
			eval "\$keymap_$_\{\$key} = " .
				($_[0] ? '$act' : 'undef');
			eval "\$keymap_$_\{'POINT'} = \$keymap_$_\{\$key}"
				if $key eq $fileptr;
		}
		$point = $file if $key eq $fileptr && $_[0];
		&setcdhist('file1', $file) if $file1 eq '';
	}
	&setcdhist('file1', $point) if $point ne '';

	foreach $key (@keys) {
		map(eval "\$keymap_$_\{\$key} = undef", keys %bagmap);
	}
}

sub win_choose {
	my($x, $y);
	foreach (@_) {
		($x, $y) = @{$drawn{$_}},
		    $scr->at($x + 2, $y + 2)
			->puts(($choose{$_} eq '') ? ' ' :
			       &color($choose{$_}, $co_decor)) if $drawn{$_};
	}
	&win_time();
}

sub win_long {
	my $row = 2;
	&win_row2() if shift;
	if ($long =~ /(^\d+$|\$_\b)/) {
		foreach (@{$lstable[0]}) {
			$scr->at($row++, $filelen + 4)->clreol()
			    ->puts(&long($longlen, $_));
		}
	} else {
		foreach (&long($longlen, @{$lstable[0]})) {
			$scr->at($row++, $filelen + 4)->clreol()->puts($_);
		}
	}
}

sub home {
	$scr->at($filerow + 3, 0)->clreol();
	$scr->puts(&scrtruncr($ch_list))->at($filerow + 3, 0) if $debug_ch;
}

sub msg {
	&home();
	$scr->puts(&color(join(' ', @_), $co_msg));
}

sub viewfile {
	my($file, $n) = @_;
	my $f; my @f = (); my $tag = '';
	$tag = &tag($file) if &opt('T');
	$n-- if $tag;
	$f =  &view($file);
        $f =~ s/[\040\240]+$/join('', map { sprintf('\\%03o', ord($_)) }
					  split(\/\/, $&))/e;
	$f =  ($f =~ /\//) ? join('', @f = &truncm($f, $n)) : &trunc($f, $n)
		if length($f) > $n;
	((&opt('C') ? &colorfile($file, $f, @f) : $f) . $tag,
	 length($f . $tag));
}

sub scrtruncr {
	substr(' ' x $scr->{COLS} . join('', @_),
	       -($scr->{COLS} - 1), $scr->{COLS});
}

###############################################################################
## Screen navigation subroutines ##############################################

sub bag {
	&win_bag(0); &page('', @_); &win_bag(1); &home();
}

sub rebag {
	&win_bag(0); @bagkeys = @_; &page(); &win_bag(1); &home();
}

sub columns {
	&filecols(@_); &win();
}

sub point {
	return &fileptr() unless @_;
	&win_bag(0, 1); &fileptr(@_); &win_bag(1, 1); &home();
}

sub page {
	my @args = @_; my %col = (); my %row = ();
	@args = @pendpage unless @args; undef @pendpage;
	@args = ($args[0], '', $args[1]) if $args[1] =~ /^[[\]{}]/;

	local $_ = shift @args;
	s/^([-+<>\[\]]?)#/$1$filecols/;
	s/^([-+<>\[\]]?)\$/$1$pages/;
	$filecol =
	    (/^$/)     ? $filecol					 :
	    (s/^\+//)  ? $filecol  + $_					 :
	    (s/^\-//)  ? $filecol  - $_					 :
	    (s/^>//)   ? ($filecol + $_) % $pages			 :
	    (s/^]//)   ? (($filecol + $_ >= $pages) ? 0 : $filecol + $_) :
	    (s/^<//)   ? ($filecol - $_) % $pages			 :
	    (s/^\[//)  ? (($filecol == 0) ? $pages - ($pages % $_ || $_) :
			  ($filecol - $_ < 0) ? 0 : $filecol - $_)	 :
	    (/^\d/)    ? $_ - 1						 :
	    (s/^\\?//) ? (($col{$_}, $row{$_}) = &pageto($_))[0]	 : 0;
	$filecol = &max(0, &min($filecol, $pages - 1));
	$filerow = ($filecol + 1 < $pages || $filerows == 0)
			? $filerows : $#ls % $filerows + 1;

	$_ = shift @args;
	s/^([-+<>]?)#/$1$filecols/;
	s/^([-+<>]?)\$/$1$pages/;
	$bagcol  =
	    (/^$/)     ? $bagcol				       :
	    (s/^\+//)  ? $bagcol  + $_				       :
	    (s/^\-//)  ? $bagcol  - $_				       :
	    (s/^>//)   ? ($bagcol + $_ - $filecol) %
			 &min($filecols, $pages - $filecol) + $filecol :
	    (s/^<//)   ? ($bagcol - $_ - $filecol) %
			 &min($filecols, $pages - $filecol) + $filecol :
	    (/^\d/)    ? $filecol + $_ - 1			       :
	    (s/^\\?//) ? ((exists $col{$_}) ? $col{$_} :
			  (($col{$_}, $row{$_}) = &pageto($_))[0])     : 0;
	$bagcol  = &max($filecol, &min($bagcol,
			&min($filecol + $filecols - 1, $pages - 1)));

	$_ = shift @args;
	s/^([-+<>]?)\$/$1$filerows/;
	$bagrows = &ceil((($bagcol < $pages - 1 || $filerows == 0) ?
			  $filerow : $#ls % $filerows + 1)
			 / ((@bagkeys) ? ($#bagkeys + 1) : 1));
	$bagrow  =
	    (/^$/)     ? $bagrow				  :
	    (s/^\+//)  ? $bagrow  + $_				  :
	    (s/^\-//)  ? $bagrow  - $_				  :
	    (s/^>//)   ? ($bagrow + $_) % $bagrows		  :
	    (s/^<//)   ? ($bagrow - $_) % $bagrows		  :
	    (s/^]//)   ? return &page('',
			     '>' . int(($bagrow + 1) / $bagrows),
			     ($bagrow + 1) % $bagrows + 1)	  :
	    (s/^\[//)  ? return &page('',
			     ($bagrow) ? '<0'    : '<1',
			     ($bagrow) ? $bagrow : "+$filerows")  :
	    (/^\d/)    ? $_ - 1					  :
	    (s/^\\?//) ? ((exists $row{$_}) ? $row{$_} :
			  (&pageto($_))[1])			  : 0;
	$bagrow  = &max(0, &min($bagrow, $bagrows - 1));
}

sub pageto {
	my $p = -1;
	foreach (@ls) {
		$p++;
		last if $_ ge $_[0];
	}
	($filerows ? int($p / $filerows) : 0,
	 int(($filerows ? $p % $filerows : 0)
	   / (@bagkeys ? ($#bagkeys + 1) : 1)));
}

sub filecols {
	local $_ = shift;
	$maxfilecols =
	    (/^$/)    ? $maxfilecols					   :
	    (s/^\+//) ? (($maxfilecols > 0) ? $maxfilecols + $_ : 0)	   :
	    (s/^\-//) ? &max(1, (($maxfilecols > 0) ? $maxfilecols
						    : $havefilecols) - $_) :
	    (s/^>//)  ? ($maxfilecols + $_) % $havefilecols		   :
	    (s/^<//)  ? ($maxfilecols - $_) % $havefilecols		   :
	    (/^\d/)   ? $_						   : 0;
	$maxfilecols = &max(0, &min($maxfilecols, $havefilecols));
}

sub fileptr {
	local $_ = shift;
	s/^([-+<>]?)\$/$1$#usedbagkeys/;
	return &cmdeval($$keymap{'POINT'}) if /^$/;
	my $n = &aindex($fileptr, @bagkeys);
	$n = 0 if $n < 0;
	$fileptr =
	    (s/^\+//)  ? $usedbagkeys[&min($n + $_, $#usedbagkeys)]	:
	    (s/^\-//)  ? $usedbagkeys[&max(0, $n - $_)]			:
	    (s/^>//)   ? $usedbagkeys[($n + $_) % ($#usedbagkeys + 1)]	:
	    (s/^<//)   ? $usedbagkeys[($n - $_) % ($#usedbagkeys + 1)]	:
	    (s/^\\?//) ? $_						: $_;
	$fileptr = $usedbagkeys[$#usedbagkeys]
		if &aindex($fileptr, @usedbagkeys) < 0;
	&setcdhist('fileptr', $fileptr);
}

sub longlen {
	local $_ = shift;
	$_ = ($minlonglen <= 57) ? 'max' : 'min' if /^t/i;
	$minlonglen =
	    (/^$/)    ? $minlonglen		       :
	    (s/^\+//) ? $minlonglen + $_	       :
	    (s/^\-//) ? $minlonglen - $_	       :
	    (/^max/i) ? $scr->{COLS} - $minfilelen - 5 :
	    (/^min/i) ? 57			       :
	    (/^\d/)   ? $_			       : 57;
	$minlonglen = &max(0, $minlonglen);
}

###############################################################################
## Color and tag subroutines ##################################################

sub tag {
	if    (-l $_[0])   { return '@' }	# -l first to force lstat
	elsif (-f _)	   { return '*' if (lstat(_))[2] & 0111 }
	elsif (-d _)	   { return '/' }
	elsif (-S _)	   { return '=' }
	elsif (-p _)	   { return '|' }
	elsif (-b _)	   { return '#' }
	elsif (-c _)	   { return '%' }
	elsif (! -e $_[0]) { return '?' }
	'';
}

sub color {
	return $_[0]	    if $_[0] eq '';
	return &colored(@_) if $color;
	($_[1] eq 'bold')    ? $bold    . $_[0] . $normal :
	($_[1] eq 'reverse') ? $reverse . $_[0] . $normal :
	($_[1] eq '')	     ?		  $_[0]		  : &colored(@_);
}

# We assume the visible segment of the given colored text does not also
# appear in either non-visible segment.
sub rl_prompt_mark_ignore {
	return $_[0] unless $rlmodule eq 'Gnu' &&
			    $_[0] ne '' && $_[0] =~ /^(.*)\Q$_[1]\E(.*)$/;
	(($1 ne '') ? "\001$1\002" : '') . $_[1] .
	(($2 ne '') ? "\001$2\002" : '');
}

sub colorfile {
	my($file, $f, @f) = @_;
	$f = $file if $f eq '';
	return &color($f, &filecolor($file)) unless $file =~ /\//;
	$f =~ /.*\//, @f = ($&, '', $')
		if $file =~ s:/:/:g eq $f =~ s:/:/:g || $f[2] =~ /\//;
	&color($f[0], &num2color($lscolors{'di'})) . $f[1] .
	&color($f[2], &filecolor($file));
}

sub filecolor {
	my $file = shift; my $c = '';

	# We sacrifice orphan detection to avoid automounts via symlinks.
	if    (-l $file)   { $c = 'ln' }  #(-e readlink $file) ? 'ln' : 'or' }
	elsif (-f _)	   { $c = 'ex' if (lstat(_))[2] & 0111 }
	elsif (-d _)	   { $c = 'di' }
	elsif (-S _)	   { $c = 'so' }
	elsif (-p _)	   { $c = 'pi' }
	elsif (-b _)	   { $c = 'bd' }
	elsif (-c _)	   { $c = 'cd' }
	elsif (! -e $file) { $c = 'mi' }
	return &num2color($lscolors{$c}) if $c;

	$c = (sort bylengthr grep(s/^\*// && substr($file, -length($_)) eq $_,
				  keys %lscolors))[0];
	return &num2color($lscolors{"*$c"}) if $c ne '';

	&num2color($lscolors{(-f _) ? 'fi' : 'no'});
}

sub bylengthr { length($b) <=> length($a) }

sub num2color {
	join(' ', map { $ansicolor{$_ + 0} } split(/;/, join(';', @_)));
}

sub lscolors {
	%lscolors = ();
	foreach (split(/:/, ($ENV{'LS_COLORS'}  || $ENV{'LS_COLOURS'})
			  . ($ENV{'LS_COLORS2'} || $ENV{'LS_COLOURS2'}))) {
		next if $_ eq '';
		my($k, $v) = split(/=/, $_, 2);
		$lscolors{$k} = $v;
	}
	%lscolors;
}

sub colorperms {
	my($t, $ur, $uw, $ux, $gr, $gw, $gx, $or, $ow, $ox) = split(//, shift);
	my($uid, $gid)					    = @_;
	my($co_u, $co_g, $co_o, $co); $co_u = $co_g = $co_o = $co_perms;
	my $co_w = ($t eq 'l') ? '' : $co_write;
	$ur = "$ur$uw";

	$t = &color($t, $co_ftype) if $co_ftype;
	if ($> == 0 || $> == $uid) {
		$co_u = $co_myper if $>;
		$gw   = &color($gw, $co)
			if $co = ($gw eq 'w' && $co_w) ? $co_w : $co_g;
		$ow   = &color($ow, $co)
			if $co = ($ow eq 'w' && $co_w) ? $co_w : $co_o;
	} elsif (grep($gid == $_, split(/\s+/, $) ))) {
		$co_g = $co_myper;
		$gw   = &color($gw, $co_g) if $co_g;
		$ow   = &color($ow, $co)
			if $co = ($ow eq 'w' && $co_w) ? $co_w : $co_o;
	} else {
		$co_o = $co_myper;
		$gw   = &color($gw, $co_g) if $co_g;
		$ow   = &color($ow, $co_o) if $co_o;
	}
	$ur = &color($ur, $co_u) if $co_u;
	$gr = &color($gr, $co_g) if $co_g;
	$or = &color($or, $co_o) if $co_o;
	$ux = &color($ux, $co)
		if $co = ($ux =~ /[st]/i && $co_sbits) ? $co_sbits : $co_u;
	$gx = &color($gx, $co)
		if $co = ($gx =~ /[st]/i && $co_sbits) ? $co_sbits : $co_g;
	$ox = &color($ox, $co)
		if $co = ($ox =~ /[st]/i && $co_sbits) ? $co_sbits : $co_o;

	"$t$ur$ux$gr$gw$gx$or$ow$ox";
}

sub colorkey {
	local $_ = join('', @_);
	return &color($_, $co_ckey) if $co_ckey && /^\^./;
	return &color($_, $co_nkey) if $co_nkey && /^\\./;
	return &color($_, $co_wkey) if $co_wkey && /^<.*>$/;
	return &color($_, $co_0key) if $co_0key && /^\d$/;
	return &color($_, $co_Akey) if $co_Akey && /^[A-Z]$/;
	return &color($_, $co_akey) if $co_akey && /^[a-z]$/;
	($co_key) ? &color($_, $co_key) : $_;
}

sub colorcmd {
	local $_ = join('', @_);
	return &color($_, $co_desc) if s/^\\//;
	my $re   = join('|', @tail); my $tail = '';
	my $com  = (s/(^|\s)(#.*)/$1/) ? $2 : '';
	eval { $tail = ($re && s/((^|;)\s*)((($re)\s*(;|$)\s*)+)$/$1/)
		       ? $3 : '' }; &err($@) if $@;
	$com  = &color($com,  $co_com)  if $co_com  && $com  ne '';
	$tail = &color($tail, $co_tail) if $co_tail && $tail ne '';
	$_    = &color($_,    $co_cmd)  if $co_cmd  && $_    ne '';
	"$_$tail$com";
}

###############################################################################
## File selection subroutines #################################################

sub dotypepath {
	my $todo = &untilde($_[0]);
	return &dotype($todo) if $todo =~ /^(\/|$)/;

	foreach ('', split(':', $ENV{'CD_PATH'})) {
		my $file = ((/./) ? &untilde($_) . '/' : '') . $todo;
		return &dotype($file) if -e $file;
	}
	&dotype($todo);
}

sub dotype {
	local  $_  = shift;	# ala csh's variable modifiers ($var:m)
	(local $_r = $_) =~ s/\.([^.]*)$//; local $_e = $1;
	local($_h, $_t);
	(/\//) ? (($_h = $_) =~ s/\/([^\/]*)$//, $_t = $1) :
		 ( $_h = '',			 $_t = $_);
	local $_f  = &absfile($_);
	local($_q, $_rq, $_eq, $_hq, $_tq, $_fq) =
		map { &quote($_) } ($_, $_r, $_e, $_h, $_t, $_f);

	@dohist = ($_f, grep($_ ne $_f, @dohist)) unless -d;
	my $max = eval $maxdohist;
	splice(@dohist, $max) if $max >= 0;
	foreach $test (sort keys %$typemap) {
		return &cmdeval($$typemap{$test}) if $test && eval $test;
	}
	&cmdeval($$typemap{''});
}

sub choose {
	&unchoose(@_), &win(), return if $altls == \@choose;

	foreach (@_) {
		next if $_ eq '';
		push(@choose, $_);
		$choose{$_} = &digit($#choose)
	}
	&win_choose(@_);
	&home();
}

sub unchoose {
	my $n	  = 0;
	@unchosen = @_ if @_;
	%choose	  = ();
	&win_choose(@choose);
	map(splice(@choose, $#choose - &aindex($_, reverse @choose), 1), @_);
	map($choose{$_} = &digit($n++), @choose);
	&win_choose(@choose);
	&home();
}

sub rechoose {
	&choose(@unchosen);
	@unchosen = ();
}

sub choosebyn {
	my $i = &undigit($_[0]);
	&home(), return if $i < 0 || $i > $#choose;

	&choose($choose[$i]), return if $altls != \@choose;

	splice(@choose, $i, 1);
	&choose();
}

sub grepls { &myeval("grep { $_[0] } \@ls") }
sub lsall  { ($altls) ? @ls : grep { ! /^\.\.?$/ } @ls }

###############################################################################
## File operation subroutines #################################################

sub untilde {
	local $_ = $_[0];
	! /^\~/ || s:^\~(\/|$):$ENV{'HOME'}$1:
		|| s:^\~([^/]+):(getpwnam($1))[7] || $&:e;
	$_;
}

sub absfile {
	my($f, $d) = @_;
	return $f if $f =~ /^\//;
	$d = $cwd if $d eq '';
	$d . (($d =~ /\/$/) ? '' : '/') . $f;
}

sub remove {
	my @bad;
	foreach (@_) {
		$! = 0;
		(-l $_ || ! -d _) ? unlink $_ : rmdir $_;
		push(@bad, "$_ ($!)") if $! + 0;
	}
	&err('Cannot remove', join(', ', @bad)) if @bad;
}

sub filecounts {
	my($d, $f, $l, $e) = (0) x 4;
	foreach (&lsall()) {
		&opt('L') ? stat $_ : lstat $_;
		(! -e _) ? $e++ : (! &opt('L') && -l _) ? $l++ :
		(  -d _) ? $d++ : $f++;
	}
	($d, $f, $l, $e);
}

sub filecount {
	my @n = &filecounts();
	join(', ', grep { ! /^0 / }
			"$n[0] director" . (($n[0] == 1) ? 'y' : 'ies'),
			"$n[1] file"	 . (($n[1] == 1) ? ''  : 's'),
			"$n[2] symlink"	 . (($n[2] == 1) ? ''  : 's'),
			"$n[3] non-existant");
}

###############################################################################
## Change directory subroutines ###############################################

sub cdpath {
	local $_ = $_[0];
	$_ = (ref eq 'HASH') ? $$_{'ls'} : (ref eq 'ARRAY') ? $$_[0] : $_;
	return &cd($_[0]) if /^(\/|$)/;

	my $pre = $err;
	foreach $dir ('', split(':', $ENV{'CD_PATH'})) {
		$err = $pre, return $cwd if &cd(((/./) ? "$dir/" : '') . $_);
	}
	$err = $pre; &err("Cannot cd $_ in CD_PATH");
	0;
}

sub cd {
	local $_ = $_[0];
	$_ = (ref eq 'HASH') ? $$_{'ls'} : (ref eq 'ARRAY') ? $$_[0] : $_;
	return 1 if $_ eq '';

	$_ = &untilde($_);
	$cwd ||= &pwd(), $_ = &absfile($_) unless /^\//;
	1 while s:/\.(/|$):/:;
	1 while s:(^|/[^/]+)/+\.\.(/|$):/:;
	s:([^/])/+$:$1:;

	&err("Cannot chdir $_ ($!)"), return 0 unless chdir $_;

	map(/^\// || ($choose{$_ = &absfile($_)} = $choose{$_}), @choose);
	map(/^\// || delete $choose{$_},		    keys %choose);
	$cwd = $_;

	my %p = (); my $p = \%p; my @new = ();
	foreach (@cdhist) { ($$_{'ls'} eq $cwd) ? do { $p = $_ unless %$p }
						: push(@new, $_) }
	%$p = %{$_[0]}, $$p{'ls'} = $cwd if ref $_[0];
	@cdhist = (%$p ? $p : {'ls' => $cwd}, @new);
	my $max = eval $maxcdhist || 1;
	splice(@cdhist, $max) if $max >= 0;
	&cdrestore(%$p ? $p : '');

	&cmdeval($onsub{'cd'}) if exists $onsub{'cd'};
	$cwd;
}

sub pwd { local $_; chomp($_ = `pwd`); $_ }

sub cdrestore {
	&page(1, 1, 1), &fileptr("-\$"), return unless my $p = shift;
	@pendpage = (($$p{'file0'} ne '') ? "\\$$p{'file0'}" : 1,
		     ($$p{'file1'} ne '') ? ("\\$$p{'file1'}",
					     "\\$$p{'file1'}") : (1, 1));
	$fileptr  = ($$p{'fileptr'} ne '') ? $$p{'fileptr'} : $bagkeys[0];
	$pendptr  = $$p{'file1'};
}

sub setcdhist {
	my($k, $v) = @_;
	($k eq 'file0')	  ? do { $file0	  = $v } :
	($k eq 'file1')	  ? do { $file1	  = $v } :
	($k eq 'fileptr') ? do { $fileptr = $v } : return;
	$cdhist[0]{$k} = $v unless $altls;
	$v;
}

sub cdhist {
	my $p;
	if ($_[0] =~ /^back$/i) {
		$p = 1;
	} elsif ($_[0] =~ /^prev$/i) {
		$p = (++$cdhistp > $#cdhist) ? '' : $cdhistp;
	} elsif ($_[0] =~ /^start$/i) {
		$p = &min($cdhistp, $#cdhist);
		$cdhistp = 0;
	}
	&cd($cdhist[$p]{'ls'});
}

###############################################################################
## Mark subroutines ###########################################################

sub setmark {
	my $mark = shift;
	return 0 if grep($mark eq $_, @_);
	$mark{$mark} = {%{$cdhist[0]}};
}

sub getmark {
	my $mark = exists $mark{$_[0]} ? $mark{$_[0]} : return undef;
	return $mark->{'ls'}				  if $_[1] =~ /^d/i;
	return $mark->{'file1'}				  if $_[1] =~ /^f/i;
	return join('/', $mark->{'ls'}, $mark->{'file1'}) if $_[1] =~ /^p/i;
	return $mark;
}

sub clearmarks { %mark = () }

sub helpmarks {
	return &pipeto(shift, "No marks are defined.\n") unless %mark;
	&help(shift,
	      map { ($_, "$mark{$_}->{ls} @ $mark{$_}->{file1}") } keys %mark);
}

###############################################################################
## Listing subroutines ########################################################

sub lsdir {
	my $dir = (@_) ? $_[0] : '.'; my @ls = ();
	&err("Cannot opendir $dir ($!)"), return @ls unless opendir DIR, $dir;
	my @dir = readdir DIR;
	closedir DIR;
	while (@dir) {
		local $_ = shift @dir;
		next if @_ && /^\.\.?$/;
		$_ = $_[0] . ((! @_ || $_[0] =~ /\/$/) ? '' : '/') . $_;
		push(@ls, $_);
		push(@ls, &lsdir($_)) if $cdhist[0]{'expand'}{$_};
	}
	@ls;
}

sub ls {
	if ($altls) {
		@ls = (ref $$altls[0] eq 'HASH')  ? map($$_{'ls'}, @$altls) :
		      (ref $$altls[0] eq 'ARRAY') ? map($$_[0],    @$altls) :
						    @$altls;
		return @ls if grep($altls == $_, \@choose, \@cdhist, \@dohist);
	} else {
		@ls = &lsdir();
	}

	&myeval("\@ls = grep { $where } \@ls") if $where =~ /\S/;
	@ls = grep(! /(^|\/)\.[^\/]*$/, @ls) if &opt('a');
	@ls = grep(! /(^|\/)\.\.?$/,    @ls) if &opt('A');
	if (&opt('B')) {
		my $bak;
		foreach $bak (@bak) {
			eval { @ls = grep(! /$bak/, @ls) };
			&err($@) if $@;
		}
	}

	%sortcache = %sortcache2 = ();
	@ls = &opt('f')			?		@ls :
	      &opt('/')			? sort bydepth	@ls :
	      &opt('F')			? sort bycolor	@ls :
	      &opt('X')			? sort byext	@ls :
	      &opt('m')			? sort bymode	@ls :
	      &opt('l')			? sort bynlink	@ls :
	      &opt('o') && ! &opt('N')	? sort byowner	@ls :
	      &opt('o') &&   &opt('N')	? sort byuid	@ls :
	      &opt('g') && ! &opt('N')	? sort bygroup	@ls :
	      &opt('g') &&   &opt('N')	? sort bygid	@ls :
	      &opt('S')			? sort bysize	@ls :
	      &opt('t')			? sort bymtime	@ls :
	      &opt('u')			? sort byatime	@ls :
	      &opt('c')			? sort byctime	@ls :
	      &opt('I')			? sort byinode	@ls :
	      &opt('b')			? sort bydot	@ls :
	      &opt('D') || &opt('d')	? sort bydir	@ls :
	      &opt('i')			? sort bynocase	@ls :
					  sort		@ls;
	%sortcache = %sortcache2 = ();
	@ls = reverse @ls if &opt('r');
	@ls;
}

sub altls {
	my $r = shift; my $old = $altls;
	$altls	 = ($r && $altls != $r) ? $r : undef;
	$lstitle = ($altls) ? join(' ', @_) : '';
	&cdrestore(($altls) ? '' : $cdhist[0]) if $altls != $old;
	&cmdeval($onsub{'altls'}) if exists $onsub{'altls'};
	$altls;
}

sub longls {
	my $win = 0; $win = shift if $_[0] =~ /^-w/;
	my $old = $long;
	if ((my $arg = join(' ', @_)) =~ /^[-+\d\s]*$/) {
		$long = ($arg =~ /^[-+]/) ? $long + $arg : $arg;
		$long = 0		    if $long < 1;
		$long = ($long - 1) % 3 + 1 if $long > 3;
		$longlabel = ('', 'user+mtime',
				  'group+atime', 'other+ctime')[$long];
	} else {
		$long = $arg . (($arg =~ /[\@\$]_/) ? '' : ' @_');
		$longlabel = "{$long}";
	}
	&page($bagcol + 1) if $long;
	(! $old || ! $long) ? &win() : do { &win_long(1); &home() }
		if $win && $old ne $long;
}

sub long {
	my $len = shift; my @ret = ();
	if ($long =~ /^\d+$/) {
		foreach (@_) {
			last if $_ eq '';
			push(@ret, &longstr($_, $len));
		}
		return @ret;
	}

	(my $cmd = $long) =~ s/\@_\b/join(' ', &quote(@_))/eg;
	if ($long =~ /\$_\b/) {
		foreach (@_) {
			last if $_ eq '';
			(my $c = $cmd) =~ s/\$_\b/&quote($_)/eg;
			push(@ret, &longfix(scalar `$c`, $_, $len));
		}
	} else {
		my @r = (@_) ? `$cmd` : ();
		foreach (@_) {
			last if $_ eq '';
			push(@ret, &longfix(shift @r, $_, $len));
		}
	}
	@ret;
}

sub longfix {
	local $_ = shift; my $label = shift; my $len = shift;
	(my $prog = $long) =~ s/^\s+//; $prog =~ s/\s.*//;
	chomp;
	s/^\Q$prog\E:\s*//mg;
	s/^\Q$label\E(:\s*|\s+)//mg;
	s/\s+\Q$label\E$//mg;
	s/\s*$//mg;
	&{$longtrunc}(&view(&expandtabs($_)), $len);
}

sub longstr {
	$! = 0;
	my($Dev, $inode, $mode, $nlink, $uid, $gid, $Rdev, $size,
	   $atime, $mtime, $ctime) = &opt('L') ? stat shift : lstat shift;
	return &color(&{$longtrunc}($!,		 $_[0]), $co_error) if $! + 0;
	return &color(&{$longtrunc}(readlink $_, $_[0]), $co_symln)
		if ! &opt('h') && ! &opt('L') && -l _;

	my $perms;
	if    (-f _)		    { $perms = '-' }
	elsif (-d _)		    { $perms = 'd' }
	elsif (! &opt('L') && -l _) { $perms = 'l' }
	elsif (-S _)		    { $perms = 's' }
	elsif (-p _)		    { $perms = 'p' }
	elsif (-b _)		    { $perms = 'b'; $size = '-' }
	elsif (-c _)		    { $perms = 'c'; $size = '-' }
	else        		    { $perms = '?' }

	$perms .= join('',
		  ('---', '--x', '-w-', '-wx', 'r--', 'r-x', 'rw-', 'rwx')
		  [($mode & 0700) >> 6, ($mode & 0070) >> 3, $mode & 0007]);
	substr($perms, 3, 1) =~ tr/-x/Ss/ if -u _;
	substr($perms, 6, 1) =~ tr/-x/Ss/ if -g _;
	substr($perms, 9, 1) =~ tr/-x/Tt/ if -k _;

	$nlink = ($nlink > 99 || $nlink < 0) ? '**' : sprintf('%2d', $nlink);

	my $user  = &opt('N') ? $uid : &uid2name($uid);
	my $group = &opt('N') ? $gid : &gid2name($gid);
	$user = ('', $user, $group, 'other')[$long];

	$size = &opt("#") ? $inode : $size;
	$user = &trunc($user, &max(8, 18 - length($size) - 1))
		if length("$user $size") > 18;
	$size = sprintf('%.' . (18 - length($user) - 7) . 'e', $size)
		if length("$user $size") > 18;
	my $usize = ' ' x 18;
	substr($usize, 0, length($user)) = $user;
	substr($usize, -length($size))   = $size if $size ne '';

	my $ftime = ('', $mtime, $atime, $ctime)[$long];
	my $ctime = &myctime($ftime);

	my $r = "$perms $nlink $usize $ctime";
	return &{$longtrunc}($r, $_[0]) if ! &opt('n') || length($r) > $_[0];

	$perms = &colorperms($perms, $uid, $gid);
	$nlink =~ s/\S+/&color($&, $co_nlink)/e if $co_nlink;

	my $co = $co_user{$user} ||
		 $co_user{('', $uid, $gid, '')[$long]} || $co_user{''};
	substr($usize, 0, length($user)) = &color($user, $co) if $co;

	if ($size =~ /^\d+$/ && ($co_size1 || $co_size2)) {
		my $n = 0; my @size = ();
		unshift(@size, &color($&, (++$n % 2) ? $co_size1
						     : $co_size2))
			while $size =~ s/.?.?.$//;
		$usize =~ s/\d+$/join('', @size)/e;
	}

	$ctime = &color($ctime, (time - $ftime > &txt2secs($aged))
				? $co_aged : $co_xaged);

	"$perms $nlink $usize $ctime";
}

sub longtrunc {
	return $longtrunc = ($longtrunc eq 'trunc') ? 'truncr' : 'trunc'
				  if $_[0] eq 'toggle';
	return $longtrunc = $_[0] if $_[0] =~ /^\w+$/ && defined &{$_[0]};
	$longtrunc = 'trunc';
}

sub txt2secs {
	local $_ = shift;
	return $_ * 31557600 if /\bye?a?r?s?\s*$/i;
	return $_ *  2629800 if /\bmon?t?h?s?\s*$/i;
	return $_ *   604800 if /\bwe?e?k?s?\s*$/i;
	return $_ *    86400 if /\bda?y?s?\s*$/i;
	return $_ *       60 if /\bmi?n?u?t?e?s?\s*$/i;
	return $_ *        1 if /\bse?c?o?n?d?s?\s*$/i;
	return $_ *     3600 if /\bh?o?u?r?s?\s*$/i;
}

###############################################################################
## Options subroutines ########################################################

sub initopts { %opts = () }

sub setopt {
	my($opt, $val) = @_;		# set opt to bool val, toggle if no val
	return(($val || ! exists $opts{$opt})
	       ? do { $opts{$opt} = 1 } : do { delete $opts{$opt}; 1 })
			if length($opt) == 1 && index($optkeys, $opt) >= 0;
	0;				# return whether valid opt
}

sub opt {
	my $opt = shift;
	return 0 unless length($opt) == 1 && index($optkeys, $opt) >= 0;
	index($optons, $opt) >= 0 xor $opts{$opt};
}

sub ifopt {
	(  &opt($_[0]))	? (($#_ >= 1) ? $_[1] : '-' . $_[0])
			: (($#_ >= 2) ? $_[2] : ());
}

sub unlessopt {
	(! &opt($_[0]))	? (($#_ >= 1) ? $_[1] : '-' . $_[0])
			: (($#_ >= 2) ? $_[2] : ());
}

###############################################################################
## Sorting subroutines ########################################################

sub byext {
	my($aext, $bext);
	$aext = '' unless ($aext = $a) =~ s/..*\.//;
	$bext = '' unless ($bext = $b) =~ s/..*\.//;
	$aext cmp $bext || &byname();
}

sub bydepth { $a =~ s:/:/:g    <=> $b =~ s:/:/:g    || &byname() }
sub bycolor { &colorval($a)    cmp &colorval($b)    || &byname() }
sub byinode { &statval($a,  1) <=> &statval($b,  1) || &byname() }
sub bymode  { &statval($b,  2) <=> &statval($a,  2) || &byname() }
sub bynlink { &statval($b,  3) <=> &statval($a,  3) || &byname() }
sub byuid   { &statval($a,  4) <=> &statval($b,  4) || &byname() }
sub bygid   { &statval($a,  5) <=> &statval($b,  5) || &byname() }
sub bysize  { &statval($b,  7) <=> &statval($a,  7) || &byname() }
sub byatime { &statval($b,  8) <=> &statval($a,  8) || &byname() }
sub bymtime { &statval($b,  9) <=> &statval($a,  9) || &byname() }
sub byctime { &statval($b, 10) <=> &statval($a, 10) || &byname() }

sub byowner { &uid2name(&statval($a, 4)) cmp &uid2name(&statval($b, 4)) ||
	      &byname() }
sub bygroup { &gid2name(&statval($a, 5)) cmp &gid2name(&statval($b, 5)) ||
	      &byname() }

sub byname  { &opt('b')		     ? &bydot() :
	      &opt('D') || &opt('d') ? &bydir() : &byascii() }

sub bydot {
	my $adot = $a =~ /^\./; my $bdot = $b =~ /^\./;
	! ($adot xor $bdot) ? (&opt('D') || &opt('d') ? &bydir() : &byascii())
			    : ($adot)		      ? 1	 : -1;
}

sub bydir {
	my $adir = &statval($a, 2, \%sortcache2) & 040000;
	my $bdir = &statval($b, 2, \%sortcache2) & 040000;
	! ($adir xor $bdir) ? &byascii() :
			      &opt('D') ? (($adir) ? -1 :  1)
					:  ($adir) ?  1 : -1;
}

sub byascii { &opt('i') ? &bynocase() : $a cmp $b }

sub bynocase {
	(my $A = $a) =~ tr/A-Z/a-z/;
	(my $B = $b) =~ tr/A-Z/a-z/;
	$A cmp $B || $a cmp $b;
}

sub colorval {
	my $f = shift;
	(exists $sortcache{$f}) ? $sortcache{$f} :
		($sortcache{$f} = &filecolor($f));
}

sub statval {
	my($f, $n) = (shift, shift);
	my($cache) = (@_) ? shift : \%sortcache;
	(exists $$cache{$f}) ? $$cache{$f} :
		($$cache{$f} = (&opt('L') ? stat $f : lstat $f)[$n]);
}

###############################################################################
## Directory expansion subroutines ############################################

sub expand	 { &expanddir('e', @_) }
sub collapse	 { &expanddir('c', @_) }
sub expandtoggle { &expanddir('t', @_) }
sub expanddir {
	return unless $depth;
	my $act = shift;	# expand || collapse || toggle
	$act = ($act =~ /^e/i) ? 1 : ($act =~ /^c/i) ? -1 : 0;
	foreach (@_) {
		my $def = exists $cdhist[0]{'expand'}{$_} unless $act;
		map($cdhist[0]{'expand'}{$_} = 1, &subdirs($_, $depth)), next
			if ($act > 0 || ! $act && ! $def) && -d $_;
		map(delete $cdhist[0]{'expand'}{$_}, &expdirs($_, $depth))
			if  $act < 0 || ! $act &&   $def;
	}
}

sub subdirs {		# depth < 0 means no limit
	my $dir = shift; my $dep = shift; my @ret = ();
	return @ret if $dep == 0; # || ! -d $dir;
	push(@ret, $dir);
	return @ret if $dep == 1 || ! opendir SUB, $dir;
	my @ls = readdir SUB;
	closedir SUB;
	while (@ls) {
		local $_ = shift @ls;
		next if /^\.\.?$/;
		$_ = $dir . (($dir =~ /\/$/) ? '' : '/') . $_;
		next if -l && ! &opt('L') || ! -d;
		push(@ret, &subdirs($_, $dep - 1));
	}
	@ret;
}

sub expdirs {
	my $dir = quotemeta shift; my $dep = shift;
	return () if $dep == 0;
	my $patt = "^$dir" . (($dep < 0) ? '(\/|$)' :
			      '(\/+[^\/]+){0,' . ($dep - 1) . '}\/*$');
	grep { /$patt/ } keys %{$cdhist[0]{'expand'}};
}

###############################################################################
## Help and prompt subroutines ################################################

sub help {	# -u* = list unused keys, -U* = list unused key ranges
	my $unused = 0; $unused = shift if $_[0] =~ /^-u/i;
	my $pager  = shift; my $tab = 8;
	my($key, $val, @kmap, @tmap); my %list = (); my @list = ();

	eval "\@kmap = \%keymap_$keymap[$#keymap]";
	eval "\@tmap = \%typemap_$typemap[$#typemap]";
	push(@_, @kmap) unless @_;
	while (@_) {
		$key = shift;
		unshift(@_, @kmap),	       next if $key eq '%keymap';
		unshift(@_, @tmap), $tab = 24, next if $key eq '%typemap';
		$val = shift;
		$list{$key} = $val unless exists $list{$key};
	}

	foreach (sort bykeyorder keys %list) {
		push(@list, &helpstr($_, '', $tab, $list{$_})) }

	if ($unused) {
		my @seq = grep(! exists $list{pack('c', $_)}, 001 .. 0177);
		@seq = &seqshort(@seq) if $unused =~ /^-U/;
		foreach (@seq) {
			$_ = &viewas(pack('c', $_)), next unless ref;
			$_ = &viewas(pack('c', $$_[0])) . '-' .
			     &viewas(pack('c', $$_[1]));
		}
		push(@list, &color('UNUSED  ' . join(' ', @seq), $co_xuse));
	}

	&pipeto($pager, @list);
}

sub bykeyorder { ($b eq '') ? -1 : ($a eq '') ? 1 :
		 (length($a) == 1 && length($b) != 1) ? -1 :
		 (length($a) != 1 && length($b) == 1) ?  1 : $a cmp $b }

sub helpstr {
	my($key, $prk, $tab, $cmd) = @_; my($v1, $v2) = (0, 0);
	return () if $cmd eq '';

	$cmd = (! ref $cmd) ? $cmd : (! ref $$cmd[0])
	       ? (($$cmd[1] ne '' && ! &opt('p'))
		  ? "\\" . eval("qq^$$cmd[1]^") : $$cmd[0])
	       : return map(&helpstr($key, substr($$_[2], 0, 1), $tab, $_),
			    &cmds($cmd));

	$key = (length($key) == 1) ? &colorkey($v1 = &viewas($key)) :
			&color($v1 = &view($key), $co_code);
	$prk = (length($prk) == 0) ? ''				    :
	       (length($prk) == 1) ? &colorkey($v2 = &viewas($prk)) :
			&color($v2 = &view($prk), $co_code);
	$key = $key . (($prk ne '') ? " $prk" : '');

	$v1  = length($v1) + (($prk ne '') ? 1 + length($v2) : 0);
	$v1  = ($v1 >= $tab) ? "\n" . ' ' x $tab : ' ' x ($tab - $v1);

	($key . $v1 . &colorcmd(&view($cmd)) . "\n");
}

sub cmdprompt {
	my($get, $cmd) = @_; my @p = (); my($v, $c, $n);
	foreach (&cmds($cmd)) {
		$n++;
		push(@p, &colorkey($v = &viewas(substr($$_[2], 0, 1))),
			 ' ' x (8 - length($v)),
			 ($$_[3] ne '') ?
				&color(&view(eval("qq^$$_[3]^")), $co_prmt) :
			 ($$_[1] ne '' && ! &opt('p')) ?
				&color(&view(eval("qq^$$_[1]^")), $co_desc) :
				&colorcmd(&view($$_[0])), "\n");
	}
	&home(); &echo(@p);
	$c   = &getkey($get);
	($filerow + 3 + $n + 1 > $scr->{ROWS}) ?
		&winch() : do { &home(); $scr->clreos() };
	$cmd = ($c eq '') ? '' : (grep { index($$_[2], $c) >= $[ } @$cmd)[0];
	$c ne "\r" && &beep(), return '' unless ref $cmd;
	$$cmd[0];
}

sub cmds {	# limited to 26 default keys (a-z), not guaranteed unique
	my $a = 'a';
	foreach $cmd (@{$_[0]}) {
		next if $$cmd[2] ne '';
		$$cmd[2] = $a++;
		last if length($a) > 1;
	}
	@{$_[0]};
}

###############################################################################
## Operation subroutines ######################################################

sub rlhistget {
	my $hist = shift;
	my $feat = $hist && $rl->Features->{'setHistory'}
			 && $rl->Features->{'getHistory'};
	$rl->SetHistory(@$hist)  if $feat;
	my $str = &getstr(@_);
	@$hist = $rl->GetHistory if $feat;
	$str;
}

sub get      { &rlhistget(\@rlhist_,	  @_) }
sub getshell { &rlhistget(\@rlhist_shell, @_) }
sub getjunk  { &rlhistget(\@rlhist_junk,  @_) }

sub getfile  {
	local $_ = &rlhistget(\@rlhist_file, @_);
	s/ $// unless s/\\ $/ /;	# clear space from filename completion
	$_;
}

sub gets {
	my $s = &get(@_);
	($filerow + 4 >= $scr->{ROWS}) ? &winch() : &home(), die "\n"
		if $s eq '';
	$s;
}

sub getcmd {
	my $cmd = join(' ', @_);
	my $arg = &get($cmd);
	($filerow + 4 >= $scr->{ROWS}) ? &winch() : &home(), die "\n"
		if $arg =~ /^\s+$/;
	$cmd . (($arg eq '') ? '' : ' ') . $arg;
}

sub getoutput {
	my @r; my $s = &getshell(@_);
	return &myeval($s) if $s =~ s/^[;:]//;
	chomp(@r = `$s`);
	@r;
}

sub ask {
	&home(), die "\n" if index('Yy' . ((length($ch) == 1 && $ch !~ /n/i) ?
					   $ch : ''), &getkey(@_)) < 0;
	&home();
}

sub shellp {	# run a command with perl if initial ";" or ":" else shell
	my $n = ($_[0] eq '-noecho') ? 1 : 0;
	return &perl(@_) if $_[$n] =~ s/^[;:]//;
	&shell(@_);
}

sub shellv {
	my $prompt = shift; my @r = ();
	my $cmd    = &getshell($prompt);
	while ($cmd !~ /^\s*([vV]|exit|lo(gout)?)\s*$/) {
		@r   = &shellp('-noecho', $cmd);
		$cmd = &getshell($prompt);
	}
	@r;
}

sub evalnext {
	my $a = shift;
	&cmdeval($$a[0]);
	push(@$a, shift @$a);
}

sub clear {
	($altls == \@cdhist)		 ? splice(@cdhist, 1) :
	($altls == \@choose || ! $altls) ? &unchoose(@choose) :
					   do { @$altls = () };
}

sub ret {
	my $prompt = join(' ', @_);
	return &getjunk($prompt) =~ /^\s*y/i if $prompt;
	my $cmd = &getshell('Press Return');
	($cmd) ? &shellp($cmd) : 0;
}

sub err {
	chomp(my $e = join(' ', @_));
	$err .= (($err ne '' && $e ne '') ? '; ' : '') . &view($e);
}

sub beep {
	print "\a";
}

###############################################################################
## Perl environment subroutines ###############################################

sub vardump {
	return '# Requires Data::Dumper module, standard with perl 5.004_71'
	     . " and later.\n" unless defined $Data::Dumper::VERSION;
	my($r)	 = '';
	local $_ = join(',', @_); s/^[\s,;]*$/\\%::/;
	foreach (grep { /./ } split(/[\s,;]+/)) {
		$r .= "# scalar, reference or object = $_\n"
		   .  Data::Dumper->new([eval $_])
				  ->Purity(1)->Terse(1)->Deepcopy(1)->Dump;
	}
	$r;
}

###############################################################################
## Disk subroutines ###########################################################

sub df {
	&err('Filesys::DiskFree not available'), return ''
		unless defined $Filesys::DiskFree::VERSION;
	$df = new Filesys::DiskFree unless $df;
	$df->df();
}

sub disks {
	return () unless &df();
	$df->disks();
}

sub diskdevs {
	return () unless &df();
	grep { /^\// && ! /^\/\// } map { $df->device($_) } $df->disks();
}

sub diskspace {
	return () unless &df();
	my @r   = ();
	my %mag = (1 => 'K', 2 => 'M', 3 => 'G', 4 => 'T');
	foreach (@_ || &pwd()) {
		my($u, $a)     = ($df->used($_), $df->avail($_));
		my($t, $f, $s) = ($u + $a, 1, '');
		foreach (reverse sort keys %mag) {
			($f, $s) = (1024 ** $_, $mag{$_}), last
				if $t > 1024 ** ($_ + 1);
		}
		push(@r, join(' ',
			sprintf("%.0f$s",	     $u / $f),	   '/',
			sprintf("%.0f$s",	     $t / $f),	   '=',
			sprintf('%.1f%%', $t ? 100 * $u / $t : 0), 'used,',
			sprintf("%.0f$s",	     $a / $f),	   'avail in',
			$df->mount($_), 'on', $df->device($_)));
	}
	$#r ? @r : shift @r;
}

###############################################################################
## System interface subroutines ###############################################

# With perl 5.8's safe signals, vshnu's behavior when suspending from within
# readline will differ.  With earlier perls, suspension is immediate.
# With perl 5.8, the suspension is postponed until a return is typed
# in readline.  This behavior is suboptimal, but tolerable.  I don't see
# a way around it.

# With perl 5.8's safe signals, vshnu's behavior when suspending from
# within a subprocess will differ.  With earlier perls, continuation works
# as expected.  With perl 5.8, continuation results in both vshnu and
# the subprocess active and sharing input.  This behavior is problematic.
# Hence the following kludge to set $SIG{'TSTP'} = 'DEFAULT' with perls
# >= 5.8.  This works at the sacrifice of directory and environment
# coordination between vshnu and its invoking shell when suspending from
# a subprocess.

sub sigs_off  { @SIG{qw/INT WINCH/} = qw/DEFAULT DEFAULT/;
		$SIG{'TSTP'}	    = ($Config{'PERL_REVISION'} >  5 ||
				       $Config{'PERL_VERSION'}  >= 8)
						? 'DEFAULT' : 'tstp' }
sub sigs_on   { @SIG{qw/INT WINCH TSTP/} = qw/IGNORE winch stop/ }
sub winch_off { $SIG{'WINCH'} = 'DEFAULT' }
sub winch_on  { $SIG{'WINCH'} = 'winch'   }

sub bakescr {
	(($_[0] =~ /./) ? $_[0] : $cooked)
		? eval { system("stty -raw echo $stty_cooked") }
		: eval { system("stty raw -echo $stty_raw") };
	# These stty commands can have the unfortunate side-effect of
	# changing a setting that the user may not want changed, even
	# outside of vshnu -- eg -istrip for 8-bit characters.  You
	# can run `setty -istrip` in tcsh, at least, to prevent it
	# from being changed in tcsh's context.  You may also define
	# $stty_cooked and $stty_raw to make corrections.
	#
	# Should we use POSIX termios here instead of `stty`?
	# See eg http://tit.irk.ru/perlbookshelf/cookbook/ch15_09.htm
	# But Term::Screen is `stty` based ...
}

sub winch {
	my $path = $ENV{'PATH'}; $ENV{'PATH'} = "/usr/ucb:$ENV{'PATH'}";
	$scr->resize();
	eval { $rl->resize_terminal() };
	$ENV{'PATH'} = $path;	# to get /usr/ucb/stty on Solaris
	&cmdeval($onsub{'winch'}) if exists $onsub{'winch'};
	&win(($_[0] == 1) ? () : ("\\$file0", "\\$file1", "\\$file1"));
}

sub getkey {
	$scr->puts(join(' ', map(&color($_, $co_decor), @_)) . ' ')
	    ->clreol() if @_;
	my $ch = $scr->getch();
	$scr->flush_input();	# partly broken in Term::Screen 1.00 *shrug*
	$ch . '';
}

sub getstr {
	&bakescr($cooked = 1);
	&winch_off();
	my $str = $rl->readline((! @_) ? '' : join(' ',
	    ($rlmodule ne 'Gnu') ? @_ :	# Perl RL breaks, but nice indic anyway
	    map(&rl_prompt_mark_ignore(&color($_, $co_decor), $_), @_)) . ' ');
	&winch_on();
	&bakescr($cooked = 0);
	$rl->addhistory($str) if $str =~ /\S/
			      && ! $rl->Features->{'autohistory'};
	$rl->SetHistory(&uniq($rl->GetHistory))
			      if $rl->Features->{'getHistory'}
			      && $rl->Features->{'setHistory'};
	$str . '';
}

sub sh {
	my $no = ($_[0] eq '-noecho') ? shift : 0;
	$scr->puts(join(' ', map(&color(&view($_), $co_decor), @_)))
	    ->clreol() unless $no;
	&bakescr($cooked = 1);
	print "\n" unless $no;
	&sigs_off();
	$! = 0;
	my @r = eval { system(@_) };
	&err("sh: $!") if $!;
	&sigs_on();
	&bakescr($cooked = 0);
	@r;
}

sub shell {
	my $no  = ($_[0] eq '-noecho') ? shift : 0;
	my $cmd = join(' ', @_);
	my $pre = $err;
	1 while $cmd =~ s/\{\{(.*?)\}\}/join(' ', &myeval($1))/e;
	return if $pre ne $err;
	$scr->puts(&color(&view($cmd), $co_decor))->clreol() unless $no;
	&bakescr($cooked = 1);
	print "\n" unless $no;
	&sigs_off();
	$! = 0;
	my @r = eval { system($shell || $ENV{'SHELL'} ||
			      '/bin/sh', '-c', $cmd) };
	&err("shell: $!") if $!;
	&sigs_on();
	&bakescr($cooked = 0);
	@r;
}

sub perl {
	my $no = ($_[0] eq '-noecho') ? shift : 0;
	$scr->puts(&color(&view(join(' ', @_)), $co_decor))->clreol() if ! $no;
	&bakescr($cooked = 1);
	print "\n" if ! $no;
	&sigs_off();
	my @r = &myeval(@_);
	&sigs_on();
	&bakescr($cooked = 0);
	@r;
}

sub echo {
	&bakescr($cooked = 1);
	print @_;
	&bakescr($cooked = 0);
}

sub pipeto {
	my $prog = shift;
	$prog = ($prog) ? "| $prog" : '> -';
	&bakescr($cooked = 1);
	&sigs_off() if $prog;
	open(PIPE, $prog) ? do { print PIPE @_; close PIPE }
			  : &err("Cannot open '$prog' ($!)");
	&sigs_on() if $prog;
	&bakescr($cooked = 0);
}

sub tstp { &stop('tstp') }

sub stop {
	&wtmpcwd()  if $tmpcwd;
	&bakescr(1) unless $_[0] eq 'tstp';
	kill 'STOP', $$;
	&bakescr()  unless $_[0] eq 'tstp';
	my $nwd;
	($nwd = &rtmpcwd()) ne $cwd && &cd($nwd), unlink $tmpcwd
		if $tmpcwd && -e $tmpcwd;
	do $tmpenv, $@ && &err($@),		  unlink $tmpenv
		if $tmpenv && -e $tmpenv;
}

sub quit {
	&onquit()  if defined &onquit;
	&wtmpcwd() if $tmpcwd;
	&bakescr(1);
	undef $scr;
	undef $rl;
	exit;
}

###############################################################################
## Master shell interface subroutines #########################################

sub rtmpcwd {
	my $r = '';
	open(TMPCWD, "< $tmpcwd") or &err("Cannot read $tmpcwd ($!)");
	chomp($r = <TMPCWD>);
	close TMPCWD;
	$r;
}

sub wtmpcwd {
	my $u = umask;
	umask 077;
	open(TMPCWD, "> $tmpcwd") or &err("Cannot write $tmpcwd ($!)");
	print TMPCWD $cwd, "\n";
	print TMPCWD join("\n", @choose), "\n";
	umask $u;
	close TMPCWD;
}

###############################################################################
## Wrapper subroutines ########################################################

sub myeval {
	my @r = eval join(' ', @_);
	&err($@) if $@;
	@r;
}

sub myctime {		# Internet (Swatch) Time
	(($_[1]) ? sprintf("@%03d ", int(($_[0] + 3600) % 86400 / 86.4)) : '')
	. localtime($_[0]);
}

sub xshell {
	&err('DISPLAY not defined'), return unless $ENV{'DISPLAY'};
	&shell(@_, '&');
}

sub uid2name {
	my($uid) = @_;
	(exists $users{$uid})  ? $users{$uid}
			       : ($users{$uid}  = (getpwuid($uid))[0] || $uid);
}

sub gid2name {
	my($gid) = @_;
	(exists $groups{$gid}) ? $groups{$gid}
			       : ($groups{$gid} = (getgrgid($gid))[0] || $gid);
}

###############################################################################
## Text subroutines ###########################################################

sub trunc {
	my($s, $n) = @_;
	return $s if length($s) <= $n;
	substr($s, 0, $n - 1) . '\\';
}

sub truncr {
	my($s, $n) = @_;
	return $s if length($s) <= $n;
	'\\' . substr($s, -($n - 1));
}

sub truncm {
	my($s, $n) = @_;
	return $s if length($s) <= $n;
	$n -= 3;
	return '' if $n < 0;
	my $p = &ceil($n / 2);
	(substr($s, 0, $p), '...', substr($s, -($n - $p), $n - $p));
}

sub quote {
	my @r = @_;
	grep { s/[^-\w\.\/]/\\$&/g } @r;
	$#r ? @r : shift @r;
}

sub evalquote {
	local $_ = join('', @_);
	s/['\\]/\\$&/g;
	"'$_'";
}

sub expandtabs {
	my $s = join('', @_);
	while ((my $t = index($s, "\t")) >= $[) {
		substr($s, $t, 1) = ' ' x (8 - $t % 8);
	}
	$s;
}

sub view {
        local $_ = join('', @_);
        s/\n/\\n/g;
        s/[\000-\007\013\016-\037\177-\237]/sprintf('\\%03o', ord($&))/eg;
        s/\010/\\b/g;	s/\f/\\f/g;
        s/\r/\\r/g;	s/\t/\\t/g;
        $_;
}

sub viewas {
        local $_ = join('', @_);
        s/\n/^J/g;
        s/[\000-\037]/'^' . pack('c', ord($&) + 64)/eg;
	s/ /<sp>/g;
	s/\177/<del>/g;
        s/[\200-\237]/sprintf('\\%03o', ord($&))/eg;
	s/\240/<nbsp>/g;
        $_;
}

###############################################################################
## General subroutines ########################################################

sub min { my $x = shift; foreach (@_) { $x = ($x <= $_) ? $x : $_ } $x }
sub max { my $x = shift; foreach (@_) { $x = ($x >= $_) ? $x : $_ } $x }

sub ceil {
	my $n = int $_[0];
	($_[0] - $n == 0) ? $n : ++$n;
}

sub digit {
	($_[0] > 60) ? '*' : (1 .. 9, 'a' .. 'z', 'A' .. 'Z')[$_[0]];
}

sub undigit {
	&aindex($_[0], (1 .. 9, 'a' .. 'z', 'A' .. 'Z'));
}

sub aindex {
	my($s, $n) = (shift, $[);
	foreach (@_) {
		last if $_ eq $s;
		$n++;
	}
	($n > $#_) ? -1 : $n;
}

sub uniq {
	my @r = ();
	foreach (@_) { unshift(@r, $_) if ! @r || $r[0] ne $_ }
	reverse @r;
}

sub seqshort {
	my @seq = @_; my @keep = ();
	while (@seq) {
		my($x, $l) = (0, 0);
		while ($l + 1 <= $#seq) {
			$l--, last if $seq[++$l] != $seq[$x] + 1;
			$x = $l;
		}
		push(@keep, ($l < 2) ? @seq[0..$l] : [$seq[0], $seq[$l]]);
		@seq = @seq[$l+1..$#seq];
	}
	@keep;
}
